name: WarpBangJaBin
version: '1.0'
main: com.rinpr.warpbangjabin.WarpBangJaBin
api-version: 1.19
commands:
  WarpBangJaBin:
    aliases: wbjb
    description: Main command for WarpBangJaBin plugin
  debug-command:

